# Generated by Django 5.2 on 2025-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
