# Generated by Django 5.2 on 2025-04-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_subscriber_tag_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
