# Generated by Django 5.2 on 2025-04-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_delete_subscriber_remove_newsitem_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='summary',
        ),
    ]
